### PR TITLE
[DOC] Update documentation

### PR DESCRIPTION
**Pull request by Remi-Gau**
## To-do / TOC

- [x] index
- [x] intro
- [x] goals
- [x] the project structure
- [x] the schema structure
- [x] schema properties
- [ ] creating a schema 
- [ ] how to to contribute
- [x] FAQ
- [ ] glossary
- [x] about this doc

## INFRA

- [x] setup automatic deploy of the mkdocs when the master branch is updated

## Related issues or PR

Primarily in this [issue](https://github.com/Remi-Gau/COBIDAS_chckls/issues/142) but see also:

- https://github.com/ReproNim/reproschema/pull/378
- https://github.com/sanuann/reproschema/pull/44

## UI documentation
- [ ] update readme (see [here](https://github.com/ReproNim/reproschema-ui/pull/148)) - PR needs review.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@satra @sanuann 

There is still much to do but maybe you can already have a look at this and make sure things are on good track in terms of content / style / tone.

**Comment by Remi-Gau** [comment]
@satra @sanuann

Thinking about to give an overview of the project, would it make sense to have an OSF project to help do that as OSF allows to have project components and have each of them track a github repo.

This is what I did for the COBIDAS (see here: https://osf.io/anvqy/) and I could try to do the same with the Reproschema.

**Comment by Remi-Gau** [comment]
Other doc related issue: 

This PR on the UI "doc" needs reviewing : https://github.com/ReproNim/reproschema-ui/pull/148

**Comment by satra** [comment]
@Remi-Gau - i think i want to stay with the docs controlling the narrative on reproschema for now before creating an OSF project. perhaps in the future, but at this point, i think github is fine.

**Comment by Remi-Gau** [comment]
> @Remi-Gau - i think i want to stay with the docs controlling the narrative on reproschema for now before creating an OSF project. perhaps in the future, but at this point, i think github is fine.

okidoki I am cool with that. :-)

**Comment by satra** [comment]
@Remi-Gau - whenever you get a chance, it would great if you can merge the PR i sent to your repo.

**Comment by Remi-Gau** [comment]
> @Remi-Gau - whenever you get a chance, it would great if you can merge the PR i sent to your repo.

@satra 
I had missed this. Thanks for pinging me. Will have a look during the weekend.

**Comment by Remi-Gau** [comment]
Did not mean to close that.

Still working on adding a few things here and there. Should I open a new PR so you can keep track?

**Comment by Remi-Gau** [comment]
I had worked on trying to make a small visualization of how the schema would map onto a "pen and paper" version to help people wrap their head around it.

This is obviously a draft.

@sanuann @satra 
What do you think? Bad idea? Good idea? What needs to be added/changed/removed ?

reproschema

**Comment by satra** [comment]
@Remi-Gau - i did open the svg to edit and then decided i had a few other things to address first  here are some thoughts that crossed my mind.

1. the left panel is a github repo. and it can show a protocol and some activities that are a local and some activities that come from a reusable library. in terms of structure, i would drop the context vs schema thing and just say schema (see the text hierarchy diagram under the schema page).
2. for a library activity we could show the paper and pencil image and indicate that the content is now in the library.
3. the ui part i like, but i wanted to show that the schema could be rendered through multiple UIs (reproschema-ui, mindlogger, etc.,.)

btw, i've just released 1.0.0-rc1 and my hope is that we can get any updates to the documentation merged in before the 1.0.0 release (say over the next two weeks).

**Comment by Remi-Gau** [comment]
>     1. the left panel is a github repo. and it can show a protocol and some activities that are a local and some activities that come from a reusable library. 

Agreed: will try to see how this can be visualized "easily".

> in terms of structure, i would drop the context vs schema thing and just say schema (see the text hierarchy diagram under the schema page).

Agreed I think I did start working on this in the pre-historic times of this repo when we still had the context files. Will drop that.


>     2. for a library activity we could show the paper and pencil image and indicate that the content is now in the library.

Agreed.
 
>     3. the ui part i like, but i wanted to show that the schema could be rendered through multiple UIs (reproschema-ui, mindlogger, etc.,.)

Are you referring to this one?
https://github.com/ReproNim/reproschema-ui/issues/4


> btw, i've just released 1.0.0-rc1 and my hope is that we can get any updates to the documentation merged in before the 1.0.0 release (say over the next two weeks).

Woohoo ! :crossed_fingers:

**Comment by Remi-Gau** [comment]
Oh actually I could make: 
- a figure to illustrate the example in the reproschema repo
-  another one showing how you can pull activities from the library.

Or would that be too much?

**Comment by satra** [comment]
perhaps before making the figure (or alongside it), creating the doc section that describes how you can create your own protocol. what are the bare bones requirements (of structuring the repo - see the demo-protocol repo), and what tools (or soon to be available tools) you can use. 

> Are you referring to this one?
ReproNim/reproschema-ui#4

acutally no just the right part of the figure you posted earlier.

> Oh actually I could make:
- a figure to illustrate the example in the reproschema repo
- another one showing how you can pull activities from the library.

i would say one figure should be sufficient. instead of the example in the reproschema repo, which is more for expanding and illustrating test cases, perhaps use the demo-protocol repo.  the demo-protocol repo should really simplify itself to demonstrating reproschema rather than a specific study (current scenario). for example, here are local new activities vs remote activities. in this local activity we are creating new items but also reusing existing items and so on. and i think this is the sentiment that has to come across in the figure.

**Comment by Remi-Gau** [comment]
- [ ] updating figure (see [above](https://github.com/ReproNim/reproschema/pull/399#issuecomment-663957417))

I started adding some tips for validation and using CI. 

Also adding some TODOs in comments for future-me.

Sorry if the way the doc grows is not the most linear: I am adding things also as a way for me to takes notes while using some "new" aspects of the reproschema.

**Comment by Remi-Gau** [comment]
In the schema structure:
- [ ] explain what terms have camelCase and which ones have PascalCase (multipleChoice vs ResponseOption)
- [ ] the current link in that page give 404 (eg. https://schema.repronim.org/ResponseOption)
- [ ] give some info on how to "read" some of those "definitions" (see below)
The following will be more useful to the users if they are sure what `rangeIncludes` and `domainIncludes` mean

```json
        {
            "@id": "schema:value",
            "schema:domainIncludes": {
                "@id": "reproschema:Choice"
            },
            "schema:rangeIncludes": [
                {
                    "@id": "reproschema:Skipped"
                },
                {
                    "@id": "reproschema:DontKnow"
                }
            ]
        }
```

**Comment by satra** [comment]
@Remi-Gau - thanks for putting this together. i think this will be good to resurrect and finish. @rahul-brito may be able to review this and add any additional materials.

**Comment by Remi-Gau** [comment]
Happy to wrap this one up.
Maybe a mini-dockathon so we can all synch up on this?

**Comment by satra** [comment]
@Rahul-Brito - can you coordinate a docathon around this ?

**Comment by Rahul-Brito** [comment]
Hi @Remi-Gau so sorry for not replying earlier. I'm a new graduate student in Satra's lab, nice to meet you. 've been trying to prioritize all the things I want to do/need to do and replying to this has been on the back of my mind for a little.

My understanding is we want to get a nice, easy-to-implement "hello world" reproschma repo up and running? If so, that sounds great to me. I have run into issues getting my own started, even with the existing documentation we have, and I can't always tell if this is user error, dependency error, etc. 

Let me know if I misunderstand!

Also, how does a dockathon compare to a hackaton :D. 

Anyways, let me know! Perhaps next week or the week after we can set something up. I will be sure to be much more responsive as well.

**Comment by Remi-Gau** [comment]
hey @Rahul-Brito 

nice to e-meet you

I suspect that finishing up all the unticked boxes in this PR could be a start as well for some doc

And a dockathon is litteraly a hackaton but where participants only work on the documentation of a project.

So 2 or 3 days where we don't write code but instead we write code comments, doc for developpers, tutorials, demos, FAQ...

**Comment by Remi-Gau** [comment]
merge conflicts fixed

moved all my stuff in a "tutorial" section

this will probably need a "refactoring"

Also need to make sure that people following the tuto would actually result in something valid: almost tempted to say that all the code snippets should actually be executable to make sure they stay valid.

Also not sure how the "linkMLification" will affect the doc.

**Pull request merged**
