### PR TITLE
Working towards a release

### PR DESCRIPTION
**Pull request by satra**
this draft PR adds a script to create a set of release files. but there is work to be done to actual cut a release for feedback.

here is the list of TODO to cut a release

updates
- [x] prefix less context #392 
- [x] update examples
- [x] update example protocol
  - [ ] test schema-ui
- [x] update library items
  - [ ] test schema-ui

release files
- [X] jsonld
- [X] ntriples
- [X] turtle
- [x] combined shacl validation file
- [x] generic context

review
- [ ] all schemas
  - [ ] comment and label
- [x] all shapes

docs
- [ ] update schema structure and properties and example @sanuann @Remi-Gau

### CODE REVIEW

**Comment by Remi-Gau** [comment]
At the moment I am pushing the doc on the PR #378 via Sanu's repo. Should I redirect it into here instead?

**Comment by satra** [comment]
> Should I redirect it into here instead?

@Remi-Gau - i don't think so yet. but it should be merged into the refactor-1.0 branch, which i will then merge into this.

**Comment by Remi-Gau** [comment]
> > Should I redirect it into here instead?
> 
> @Remi-Gau - i don't think so yet. but it should be merged into the refactor-1.0 branch, which i will then merge into this.

OK I will get back to this now that created some sort of **documentation to-do list** for this in [this issue](https://github.com/Remi-Gau/COBIDAS_chckls/issues/142).

**Comment by Remi-Gau** [comment]
**More TO DO**

- [ ] create a `MultiFloatInput` inputType (#404)

**Comment by satra** [comment]
@sanuann - please check if all of the items here have been completed.

**Comment by Remi-Gau** [comment]
**UI TO DO**

not sure those are needed for the Refactor 1.0 but in-case I am adding them here:
- [ ] make the timeRange input more general ( see [here](https://github.com/ReproNim/reproschema-ui/issues/151))
- [ ] support for structured output (see [here](https://github.com/ReproNim/reproschema-ui/issues/152))

**Pull request merged**
