### PR TITLE
adding CreativeWork to most of the classes

### PR DESCRIPTION
**Pull request by djarecka**
- adding CreativeWork to most of the classes
- adding description to CreativeWork slots
- slightly different formatting from  the linkml generator

@satra - could you please see the descriptions of `id` and `category`, I've realized that there is no `schema:id` just `schema:identifier`. Also not  completely sure about the category, since I haven't seen an example

### CODE REVIEW

**Comment by satra** [comment]
@djarecka - i should have been more careful. not every class can be creativework. take a look at schema:CreativeWork. for example, schema.org has elements that derive directly from Thing (e.g. Person), others that derive from CreativeWork and others that derive from Property. hence for each element in reproschema a modeling decision has to be taken as to whether it fits into the definition of a `schema:CreativeWork`. 

we should introduce a `Thing` or `NamedThing` class in reproschema linkml from which most things could be derived. 

for `category` and `id` i would simply suggest checking out the biolink definitions (e.g., https://biolink.github.io/biolink-model/category/#linkml-source). i would also suggest looking at some of the other properties in the definitions. linkml provides several attributes to increase richness of the definition.

**Comment by djarecka** [comment]
> @djarecka - i should have been more careful. not every class can be creativework. take a look at schema:CreativeWork. for example, schema.org has elements that derive directly from Thing (e.g. Person), others that derive from CreativeWork and others that derive from Property. hence for each element in reproschema a modeling decision has to be taken as to whether it fits into the definition of a `schema:CreativeWork`.
ok, I actually didn't add `CreativeWork` to the `Participant` since it seemed wrong to me. I kept `is_a: Agent`.

> 
> we should introduce a `Thing` or `NamedThing` class in reproschema linkml from which most things could be derived.
> 
> for `category` and `id` i would simply suggest checking out the biolink definitions (e.g., https://biolink.github.io/biolink-model/category/#linkml-source). i would also suggest looking at some of the other properties in the definitions. linkml provides several attributes to increase richness of the definition.

Ok, I will look at the definitions from the biolink schema. 

Questions related to `CreativeWork` and `NamedThings`.
- the way how `CreativeWork` is defined in reproscheman right now, it could be easily called just `NamedThing`, so perhaps the first step would be removing `CreativeWork` and just use `NamedThing`
- We could add more thing to `CreativeWork` and use it in some classes in `is_a` instead of `NamedThing`, but do you want to do add teh changes now, or after the move to linkml?
-

**Comment by djarecka** [comment]
@satra - I added `Thing` and change some classes to inherit from `Thing` instead of `CreativeWork`.
I haven't added too many properties to `CreativeWork`, since even adding the simplest property like `author` would require adding `Person` and `Organization` and don't want to do it here

**Comment by djarecka** [comment]
@satra - I will merge it if you don't leave any comments. we can always do more later

**Review by satra — COMMENTED** [review]
do you know why `id` and `name` are being added to every class instead of using inheritance? is that a linkml pydantic thing?

**Comment by djarecka** [comment]
> do you know why `id` and `name` are being added to every class instead of using inheritance? is that a linkml pydantic thing?

it is linkml-pydantic thing

**Review by satra — APPROVED** [review]

**Pull request merged**
